name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # change if your backend deploy branch is different

jobs:
  deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest

    env:
      FUNCTIONS_EMULATOR: false  # Set to true if you want to test locally before deploying

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or 20 depending on your firebase functions runtime

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions dependencies
        run: |
          cd functions
          npm ci

      - name: Deploy to Firebase Functions
        run: |
          cd functions
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
