name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or 20, depending on your functions' runtime

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: cd backend/functions && npm ci

      - name: Deploy to Firebase
        run: cd backend/functions && firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
